- name: Install package list - i3
  dnf: name={{item}} state=installed
  with_items:
    - i3
    - i3-ipc
    - i3lock
    - i3status
    - dmenu
    - dunst
    - nitrogen
    - sakura
    - terminology
    - roxterm
    - st
    - termit
    - gnome-terminal
    - firefox
    - icecat
    - midori
    - qutebrowser
    - epiphany
    - camorama
    - shotwell
    - parole
    - evince
    - eom
    - arandr
    - scrot
    - ranger
    - gnome-keyring
    - gnome-keyring-pam
    - NetworkManager
    - NetworkManager-tui
    - NetworkManager-vpnc
    - NetworkManager-vpnc-gnome
    - NetworkManager-openvpn
    - NetworkManager-openvpn-gnome
    - pidgin
    - geany
    - geany-plugins-markdown
    - geany-plugins-autoclose
    - geany-plugins-defineformat
    - geany-plugins-scope
    - pulseaudio-module-bluetooth
    - paman
    - blueman
    - clementine
    - ImageMagick
    - ImageMagick-devel
    - transmission
    - transmission-gtk
    - arduino
    - ino
    - hplip-gui
    - hplip-common
    - hplip-libs

- name: Install MATE for use with i3
  dnf: name="@mate-desktop" state=installed

- name: Install MATE Applications for use with i3
  dnf: name="@mate-applications" state=installed


# vim:ft=ansible: